# Generated by Django 5.2.7 on 2025-10-24 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_created_at_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booked_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='student',
            new_name='tutee',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='max_students',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='subject',
        ),
        migrations.AddField(
            model_name='booking',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slot',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.slot'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tutee', 'Tutee'), ('tutor', 'Tutor')], default='tutee', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
