# Generated by Django 5.2 on 2025-10-30 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_slot_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='end',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='max_students',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='slot',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.slot'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tutee', 'Tutee'), ('tutor', 'Tutor'), ('both', 'Both')], default='tutee', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
