# Generated by Django 5.2 on 2025-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_email_verified_profile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
